"""domain_models

Revision ID: 106b006549ce
Revises: 0001
Create Date: 2026-09-14 14:57:15.638882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106b006549ce'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='analytics'
    )
    op.create_table('lead_time_definition',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_event', sa.String(), nullable=False),
    sa.Column('end_event', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='analytics'
    )
    op.create_table('audit_event',
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('vessel_call',
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('imo_number', sa.String(), nullable=True),
    sa.Column('vcn', sa.String(), nullable=True),
    sa.Column('vessel_type', sa.String(), nullable=True),
    sa.Column('vessel_size_teu', sa.Integer(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('last_port_of_call', sa.String(), nullable=True),
    sa.Column('next_port_of_call', sa.String(), nullable=True),
    sa.Column('port_of_lading', sa.String(), nullable=True),
    sa.Column('port_of_discharge', sa.String(), nullable=True),
    sa.Column('reason_for_visit', sa.String(), nullable=True),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('quantity_value', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sa.String(), nullable=True),
    sa.Column('grt', sa.Float(), nullable=True),
    sa.Column('loa_value', sa.Float(), nullable=True),
    sa.Column('loa_unit', sa.String(), nullable=True),
    sa.Column('dwt', sa.Float(), nullable=True),
    sa.Column('forward_draft_value', sa.Float(), nullable=True),
    sa.Column('forward_draft_unit', sa.String(), nullable=True),
    sa.Column('aft_draft_value', sa.Float(), nullable=True),
    sa.Column('aft_draft_unit', sa.String(), nullable=True),
    sa.Column('call_sign', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vcn'),
    schema='canonical'
    )
    op.create_table('event_definition',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='config'
    )
    op.create_table('match_candidate',
    sa.Column('source_record_1_id', sa.String(), nullable=False),
    sa.Column('source_record_2_id', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('journey_template',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dag_definition', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='journey'
    )
    op.create_table('quality_rule',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('pass_fail_expression', sa.String(), nullable=False),
    sa.Column('remediation_guidance', sa.String(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id'),
    schema='quality'
    )
    op.create_table('dq_case',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expected_outcome', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='testkit'
    )
    op.create_table('expected_output',
    sa.Column('vcn', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='testkit'
    )
    op.create_table('kpi_formula_version',
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['analytics.kpi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('kpi_result',
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('vessel_call_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['analytics.kpi.id'], ),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['canonical.vessel_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('lead_time_result',
    sa.Column('vessel_call_id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['analytics.lead_time_definition.id'], ),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['canonical.vessel_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('delay',
    sa.Column('vessel_call_id', sa.UUID(), nullable=False),
    sa.Column('movement_stage', sa.String(), nullable=False),
    sa.Column('total_duration_hours', sa.Float(), nullable=False),
    sa.Column('is_early_service', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['canonical.vessel_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='canonical'
    )
    op.create_table('event_occurrence',
    sa.Column('vessel_call_id', sa.UUID(), nullable=False),
    sa.Column('event_definition_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=False),
    sa.Column('movement_scope', sa.String(), nullable=False),
    sa.Column('original_string', sa.String(), nullable=True),
    sa.Column('parsed_value', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_timezone', sa.String(), nullable=True),
    sa.Column('utc_value', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_method', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('ingestion_batch_id', sa.String(), nullable=True),
    sa.Column('correction_history', sa.JSON(), nullable=True),
    sa.Column('inference_status', sa.String(), nullable=True),
    sa.Column('human_review_state', sa.String(), nullable=True),
    sa.Column('is_quarantined', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_definition_id'], ['config.event_definition.id'], ),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['canonical.vessel_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_call_id', 'event_definition_id', 'occurrence_index', name='uq_event_occurrence'),
    schema='canonical'
    )
    op.create_table('service_request',
    sa.Column('vessel_call_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('requested_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['canonical.vessel_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='canonical'
    )
    op.create_table('event_alias',
    sa.Column('event_definition_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('confirmation_state', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_definition_id'], ['config.event_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='config'
    )
    op.create_table('match_evidence',
    sa.Column('match_candidate_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('evidence_detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_candidate_id'], ['identity.match_candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('merge_decision',
    sa.Column('match_candidate_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('is_reversible', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_candidate_id'], ['identity.match_candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('journey_instance',
    sa.Column('vessel_call_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['journey.journey_template.id'], ),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['canonical.vessel_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='journey'
    )
    op.create_table('journey_stage',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['journey.journey_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='journey'
    )
    op.create_table('quality_issue',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('vessel_call_id', sa.UUID(), nullable=True),
    sa.Column('record_reference', sa.String(), nullable=False),
    sa.Column('issue_status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['quality.quality_rule.id'], ),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['canonical.vessel_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_table('delay_allocation',
    sa.Column('delay_id', sa.UUID(), nullable=False),
    sa.Column('cause', sa.String(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('cause_status', sa.String(), nullable=True),
    sa.Column('inference_evidence', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delay_id'], ['canonical.delay.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='canonical'
    )
    op.create_table('service_assignment',
    sa.Column('service_request_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_resource_id', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['canonical.service_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='canonical'
    )
    op.create_table('stage_occurrence',
    sa.Column('journey_instance_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_instance_id'], ['journey.journey_instance.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['journey.journey_stage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='journey'
    )
    op.create_table('resolution_decision',
    sa.Column('quality_issue_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quality_issue_id'], ['quality.quality_issue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_table('service_execution',
    sa.Column('service_assignment_id', sa.UUID(), nullable=False),
    sa.Column('served_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_assignment_id'], ['canonical.service_assignment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='canonical'
    )
    op.create_table('handover',
    sa.Column('from_stage_occurrence_id', sa.UUID(), nullable=False),
    sa.Column('to_stage_occurrence_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_stage_occurrence_id'], ['journey.stage_occurrence.id'], ),
    sa.ForeignKeyConstraint(['to_stage_occurrence_id'], ['journey.stage_occurrence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='journey'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handover', schema='journey')
    op.drop_table('service_execution', schema='canonical')
    op.drop_table('resolution_decision', schema='quality')
    op.drop_table('stage_occurrence', schema='journey')
    op.drop_table('service_assignment', schema='canonical')
    op.drop_table('delay_allocation', schema='canonical')
    op.drop_table('quality_issue', schema='quality')
    op.drop_table('journey_stage', schema='journey')
    op.drop_table('journey_instance', schema='journey')
    op.drop_table('merge_decision', schema='identity')
    op.drop_table('match_evidence', schema='identity')
    op.drop_table('event_alias', schema='config')
    op.drop_table('service_request', schema='canonical')
    op.drop_table('event_occurrence', schema='canonical')
    op.drop_table('delay', schema='canonical')
    op.drop_table('lead_time_result', schema='analytics')
    op.drop_table('kpi_result', schema='analytics')
    op.drop_table('kpi_formula_version', schema='analytics')
    op.drop_table('expected_output', schema='testkit')
    op.drop_table('dq_case', schema='testkit')
    op.drop_table('quality_rule', schema='quality')
    op.drop_table('journey_template', schema='journey')
    op.drop_table('match_candidate', schema='identity')
    op.drop_table('event_definition', schema='config')
    op.drop_table('vessel_call', schema='canonical')
    op.drop_table('audit_event', schema='audit')
    op.drop_table('lead_time_definition', schema='analytics')
    op.drop_table('kpi', schema='analytics')
    # ### end Alembic commands ###
