"""auth_rbac_models

Revision ID: 6dca3a102f22
Revises: 384d7f763123
Create Date: 2026-09-14 15:06:53.923777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dca3a102f22'
down_revision: Union[str, Sequence[str], None] = '384d7f763123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action'),
    schema='config'
    )
    op.create_table('role',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='config'
    )
    op.create_table('session',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    schema='config'
    )
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('terminal_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='config'
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['config.permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['config.role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='config'
    )
    op.create_table('service_account',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('terminal_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['config.role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    schema='config'
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['config.role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['config.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='config'
    )
    op.add_column('audit_event', sa.Column('actor_id', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('actor_email', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('actor_role', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('resource_type', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('resource_id', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('correlation_id', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('ip_address', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('user_agent', sa.String(), nullable=True), schema='audit')
    op.add_column('audit_event', sa.Column('details', sa.JSON(), nullable=True), schema='audit')
    op.alter_column('audit_event', 'entity_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='audit')
    op.alter_column('audit_event', 'entity_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='audit')
    op.alter_column('audit_event', 'changes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='audit')
    op.add_column('vessel_call', sa.Column('tenant_id', sa.String(), nullable=False), schema='canonical')
    op.add_column('vessel_call', sa.Column('port_id', sa.String(), nullable=True), schema='canonical')
    op.add_column('vessel_call', sa.Column('terminal_id', sa.String(), nullable=True), schema='canonical')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vessel_call', 'terminal_id', schema='canonical')
    op.drop_column('vessel_call', 'port_id', schema='canonical')
    op.drop_column('vessel_call', 'tenant_id', schema='canonical')
    op.alter_column('audit_event', 'changes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='audit')
    op.alter_column('audit_event', 'entity_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='audit')
    op.alter_column('audit_event', 'entity_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='audit')
    op.drop_column('audit_event', 'details', schema='audit')
    op.drop_column('audit_event', 'user_agent', schema='audit')
    op.drop_column('audit_event', 'ip_address', schema='audit')
    op.drop_column('audit_event', 'correlation_id', schema='audit')
    op.drop_column('audit_event', 'resource_id', schema='audit')
    op.drop_column('audit_event', 'resource_type', schema='audit')
    op.drop_column('audit_event', 'actor_role', schema='audit')
    op.drop_column('audit_event', 'actor_email', schema='audit')
    op.drop_column('audit_event', 'actor_id', schema='audit')
    op.drop_table('user_role', schema='config')
    op.drop_table('service_account', schema='config')
    op.drop_table('role_permission', schema='config')
    op.drop_table('user', schema='config')
    op.drop_table('session', schema='config')
    op.drop_table('role', schema='config')
    op.drop_table('permission', schema='config')
    # ### end Alembic commands ###
