"""Add ingestion models

Revision ID: 765a0f78f308
Revises: 6dca3a102f22
Create Date: 2026-09-14 15:25:46.406356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765a0f78f308'
down_revision: Union[str, Sequence[str], None] = '6dca3a102f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_template',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('worksheet_name', sa.String(), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='config'
    )
    op.create_table('batch',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_checksum', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id'),
    schema='raw'
    )
    op.create_table('record',
    sa.Column('file_checksum', sa.String(), nullable=False),
    sa.Column('worksheet_name', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('ingestion_batch_id', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('record',
    sa.Column('file_checksum', sa.String(), nullable=False),
    sa.Column('worksheet_name', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('ingestion_batch_id', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('canonical_table', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_lineage_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record', schema='staging')
    op.drop_table('record', schema='raw')
    op.drop_table('batch', schema='raw')
    op.drop_table('import_template', schema='config')
    # ### end Alembic commands ###
