"""Drop VCN unique constraint

Revision ID: 9f5f942e63de
Revises: 765a0f78f308
Create Date: 2026-09-14 15:34:47.980198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5f942e63de'
down_revision: Union[str, Sequence[str], None] = '765a0f78f308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vessel_call_vcn_key'), 'vessel_call', schema='canonical', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vessel_call_vcn_key'), 'vessel_call', ['vcn'], schema='canonical', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
