"""Governed KPI Registry (spec §11, phase-08-kpi-engine.md).

Defines all 55 KPIs from spec §11 with business definitions, formulas, numerators,
denominators, units, eligibility, exclusions, aggregation methods, targets, thresholds,
and availability status (COMPUTED vs NO_SOURCE_DATA).
Preserves the spec's KPI numbering (KPI-01 to KPI-55) and prevents double-counting by
designating primary and alias pairs (KPI-11/KPI-53, KPI-14/KPI-51).
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from sqlalchemy import select
from sqlalchemy.orm import Session

from apps.api.models.analytics import KPI, KPIFormulaVersion

# Governed catalogue of all 55 KPIs from spec §11
KPI_REGISTRY_DEFINITIONS: List[Dict[str, Any]] = [
    # ── Pre-arrival and anchorage ─────────────────────────────────────────────
    {
        "kpi_number": 1,
        "code": "KPI-01",
        "name": "Number of Vessel Calls",
        "category": "Pre-arrival and anchorage",
        "description": "Total count of unique vessel arrivals completed within the reporting period.",
        "formula": "COUNT(DISTINCT vessel_call_id)",
        "numerator": "Unique vessel arrivals",
        "denominator": "None (integer count)",
        "unit": "calls",
        "aggregation_method": "COUNT",
        "eligible_population": "All active unmerged vessel calls with recorded ATA",
        "required_events": ["ATA"],
        "required_fields": ["vcn"],
        "exclusions": ["Quarantined records", "Merged duplicates"],
        "target": 75.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 70.0, "amber": 60.0, "red": 50.0},
        "owner": "Marine Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 2,
        "code": "KPI-02",
        "name": "Average Vessel Call Size",
        "category": "Pre-arrival and anchorage",
        "description": "Total cargo handled divided by vessel calls, strictly segmented by unit (TEU, MT, or Units). Never mixes units into an unqualified total.",
        "formula": "SUM(actual_quantity) / COUNT(DISTINCT vessel_call_id) [by unit]",
        "numerator": "Sum of actual cargo quantity for specified cargo unit",
        "denominator": "Distinct vessel calls carrying that cargo unit",
        "unit": "TEU/call or MT/call",
        "aggregation_method": "AVG",
        "eligible_population": "Vessel calls with valid cargo operations in the specified unit",
        "required_events": ["CARGO_START", "CARGO_END"],
        "required_fields": ["actual_quantity", "unit"],
        "exclusions": ["Calls without cargo records in matching unit"],
        "target": 15000.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 12000.0, "amber": 8000.0, "red": 5000.0},
        "owner": "Commercial Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 3,
        "code": "KPI-03",
        "name": "Average Pre-Berthing Waiting Time",
        "category": "Pre-arrival and anchorage",
        "description": "Total pre-berthing waiting time at anchorage prior to pilot boarding divided by eligible vessels.",
        "formula": "SUM(PILOT_ON_BOARD_ARRIVAL - ANCHORAGE_ARRIVAL) / COUNT(eligible_vessels)",
        "numerator": "Sum of anchorage wait hours",
        "denominator": "Vessels calling at anchorage",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Vessels anchoring before pilot boarding",
        "required_events": ["ANCHORAGE_ARRIVAL", "PILOT_ON_BOARD_ARRIVAL"],
        "required_fields": ["utc_value"],
        "exclusions": ["Direct berthing calls without anchorage stay", "Quarantined chronology defects"],
        "target": 4.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 5.0, "amber": 10.0, "red": 24.0},
        "owner": "Harbour Master",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 4,
        "code": "KPI-04",
        "name": "Pre-Berthing Delay",
        "category": "Pre-arrival and anchorage",
        "description": "Average elapsed interval between Anchorage Arrival and First Mooring Line Tied (Berth Commencement).",
        "formula": "AVG(FIRST_LINE_TIED_ARRIVAL - ANCHORAGE_ARRIVAL)",
        "numerator": "Sum of elapsed hours from anchorage to first line tied",
        "denominator": "Count of eligible anchored vessels",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Anchored vessels completing inward berthing",
        "required_events": ["ANCHORAGE_ARRIVAL", "FIRST_LINE_TIED_ARRIVAL"],
        "required_fields": ["utc_value"],
        "exclusions": ["Quarantined chronology defects"],
        "target": 6.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 6.0, "amber": 12.0, "red": 24.0},
        "owner": "Harbour Master",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 5,
        "code": "KPI-05",
        "name": "Anchorage Time Variation Index",
        "category": "Pre-arrival and anchorage",
        "description": "Standard deviation of anchorage waiting duration (Pilot Boarding - Anchorage Arrival), segmented by vessel type.",
        "formula": "STDDEV(PILOT_ON_BOARD_ARRIVAL - ANCHORAGE_ARRIVAL)",
        "numerator": "Standard deviation of wait duration",
        "denominator": "N/A (dispersion measure)",
        "unit": "hours",
        "aggregation_method": "STDDEV",
        "eligible_population": "Vessel calls with verified anchorage stay",
        "required_events": ["ANCHORAGE_ARRIVAL", "PILOT_ON_BOARD_ARRIVAL"],
        "required_fields": ["utc_value"],
        "exclusions": ["Single-call cohorts where N < 2"],
        "target": 2.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 2.5, "amber": 5.0, "red": 10.0},
        "owner": "Harbour Master",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 6,
        "code": "KPI-06",
        "name": "VTS Clearance Time",
        "category": "Pre-arrival and anchorage",
        "description": "Average duration from Anchorage Arrival to VTS Clearance confirmation.",
        "formula": "AVG(VTS_CLEARANCE - ANCHORAGE_ARRIVAL)",
        "numerator": "Sum of clearance intervals",
        "denominator": "Count of cleared calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Vessels requiring formal VTS clearance",
        "required_events": ["ANCHORAGE_ARRIVAL", "VTS_CLEARANCE"],
        "required_fields": ["utc_value"],
        "exclusions": ["Calls lacking explicit VTS log"],
        "target": 0.5,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 0.5, "amber": 1.0, "red": 2.0},
        "owner": "VTS Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["VTS_RADAR_LOG"],
        "is_primary": True,
    },

    # ── Inward movement ───────────────────────────────────────────────────────
    {
        "kpi_number": 7,
        "code": "KPI-07",
        "name": "Average Inward Movement Time",
        "category": "Inward movement",
        "description": "Inward transit time from Pilot On Board at anchorage to All Fast at berth.",
        "formula": "AVG(ALL_FAST_ARRIVAL - PILOT_ON_BOARD_ARRIVAL)",
        "numerator": "Sum of inward transit durations",
        "denominator": "Count of berthed vessel calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Berthed vessels with pilotage arrival service",
        "required_events": ["PILOT_ON_BOARD_ARRIVAL", "ALL_FAST_ARRIVAL"],
        "required_fields": ["utc_value"],
        "exclusions": ["Vessels anchoring inside harbour without pilot", "Quarantined events"],
        "target": 1.5,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 1.5, "amber": 2.5, "red": 4.0},
        "owner": "Marine Pilotage",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 8,
        "code": "KPI-08",
        "name": "Average Inward Towage Duration",
        "category": "Inward movement",
        "description": "Summed inward tug service duration divided by assisted vessels or service instances. Denominator choice is disclosed on result.",
        "formula": "SUM(tug_duration) / COUNT(assisted_vessels)",
        "numerator": "Total tug service hours on arrival",
        "denominator": "Count of assisted vessel calls (default)",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Arrival movements requiring towage assistance",
        "required_events": ["TUG_SERVICE_START_ARRIVAL", "ALL_FAST_ARRIVAL"],
        "required_fields": ["service_type"],
        "exclusions": ["Unassisted berthing calls"],
        "target": 1.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 1.2, "amber": 2.0, "red": 3.0},
        "owner": "Towage Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 9,
        "code": "KPI-09",
        "name": "Tug Availability",
        "category": "Inward movement",
        "description": "Available tug service hours divided by requested tug hours expressed as percentage.",
        "formula": "(available_tug_hours / requested_tug_hours) * 100",
        "numerator": "Served tug hours without delay",
        "denominator": "Total requested tug hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "All towage service orders",
        "required_events": [],
        "required_fields": ["service_type", "requested_time", "served_time"],
        "exclusions": ["Cancelled service requests"],
        "target": 98.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 95.0, "amber": 90.0, "red": 80.0},
        "owner": "Towage Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 10,
        "code": "KPI-10",
        "name": "Pilot Availability",
        "category": "Inward movement",
        "description": "Available pilot hours divided by requested pilot hours expressed as percentage.",
        "formula": "(available_pilot_hours / requested_pilot_hours) * 100",
        "numerator": "Served pilotage hours without delay",
        "denominator": "Total requested pilotage hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "All pilotage service requests",
        "required_events": [],
        "required_fields": ["service_type", "requested_time", "served_time"],
        "exclusions": ["Cancelled service requests"],
        "target": 98.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 95.0, "amber": 90.0, "red": 80.0},
        "owner": "Marine Pilotage",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 11,
        "code": "KPI-11",
        "name": "Tug Response Time",
        "category": "Inward movement",
        "description": "Average duration from Tug Request to Tug Arrival on scene. (Primary metric for tug responsiveness; alias is KPI-53).",
        "formula": "AVG(Tug_Arrival - Tug_Request)",
        "numerator": "Sum of tug response intervals",
        "denominator": "Total tug requests served",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Towage service requests with arrival logged",
        "required_events": [],
        "required_fields": ["requested_time", "served_time"],
        "exclusions": [],
        "target": 0.75,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 0.8, "amber": 1.5, "red": 2.5},
        "owner": "Towage Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 12,
        "code": "KPI-12",
        "name": "Pilot Boarding Time",
        "category": "Inward movement",
        "description": "Average duration between Pilot Assigned / Scheduled and Pilot On Board.",
        "formula": "AVG(PILOT_ON_BOARD - PILOT_SCHEDULED)",
        "numerator": "Sum of pilot boarding intervals",
        "denominator": "Count of pilot boarding events",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Pilotage assignments with confirmed boarding",
        "required_events": ["PILOT_SCHEDULED_ARRIVAL", "PILOT_ON_BOARD_ARRIVAL"],
        "required_fields": ["scheduled_time", "served_time"],
        "exclusions": ["Cancelled pilot movements"],
        "target": 0.5,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 0.5, "amber": 1.0, "red": 2.0},
        "owner": "Marine Pilotage",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 13,
        "code": "KPI-13",
        "name": "Pilot-to-Berth Time",
        "category": "Inward movement",
        "description": "Average navigation duration from Pilot On Board at seaward station to All Fast alongside berth.",
        "formula": "AVG(ALL_FAST_ARRIVAL - PILOT_ON_BOARD_ARRIVAL)",
        "numerator": "Sum of pilot inward transit durations",
        "denominator": "Total completed inward transits",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Vessels completing piloted inward transit",
        "required_events": ["PILOT_ON_BOARD_ARRIVAL", "ALL_FAST_ARRIVAL"],
        "required_fields": ["utc_value"],
        "exclusions": ["Quarantined events"],
        "target": 1.25,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 1.3, "amber": 2.0, "red": 3.0},
        "owner": "Marine Pilotage",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },

    # ── Berthing and at berth ─────────────────────────────────────────────────
    {
        "kpi_number": 14,
        "code": "KPI-14",
        "name": "Berth Occupancy Rate",
        "category": "Berthing and at berth",
        "description": "Occupied berth hours divided by available berth hours over the period * 100. (Primary metric; alias is KPI-51).",
        "formula": "(SUM(berth_stay_hours) / available_berth_hours) * 100",
        "numerator": "Total hours berths were occupied by active calls",
        "denominator": "Total theoretical capacity hours for active berths in period",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Active commercial berths",
        "required_events": ["ALL_FAST_ARRIVAL", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["utc_value"],
        "exclusions": ["Berths under scheduled capital dredging or civil repair"],
        "target": 65.0,
        "target_direction": "BAND",
        "thresholds": {"green": 70.0, "amber": 80.0, "red": 90.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 15,
        "code": "KPI-15",
        "name": "Average Berthing Time",
        "category": "Berthing and at berth",
        "description": "Total alongside berth duration divided by vessel count.",
        "formula": "AVG(LAST_LINE_UNTIED_SAILING - ALL_FAST_ARRIVAL)",
        "numerator": "Sum of all berth stays",
        "denominator": "Count of berthed calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Completed vessel calls alongside",
        "required_events": ["ALL_FAST_ARRIVAL", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["utc_value"],
        "exclusions": ["Quarantined calls"],
        "target": 24.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 24.0, "amber": 48.0, "red": 72.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 16,
        "code": "KPI-16",
        "name": "Berthing Time Variation Index",
        "category": "Berthing and at berth",
        "description": "Standard deviation of alongside berth stay across vessel types.",
        "formula": "STDDEV(LAST_LINE_UNTIED_SAILING - ALL_FAST_ARRIVAL)",
        "numerator": "Standard deviation of alongside stay",
        "denominator": "N/A (dispersion measure)",
        "unit": "hours",
        "aggregation_method": "STDDEV",
        "eligible_population": "Completed berthed calls",
        "required_events": ["ALL_FAST_ARRIVAL", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["utc_value"],
        "exclusions": ["Cohorts with N < 2"],
        "target": 12.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 12.0, "amber": 24.0, "red": 48.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 17,
        "code": "KPI-17",
        "name": "Average Non-Working Time at Berth",
        "category": "Berthing and at berth",
        "description": "Total non-working alongside time (Berth Stay minus Cargo Working duration) divided by vessels.",
        "formula": "AVG((LAST_LINE_UNTIED - ALL_FAST) - (CARGO_END - CARGO_START))",
        "numerator": "Sum of non-working buffer hours",
        "denominator": "Completed vessel calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Calls with recorded cargo operations",
        "required_events": ["ALL_FAST_ARRIVAL", "CARGO_START", "CARGO_END", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["utc_value"],
        "exclusions": ["Calls without cargo operations (e.g. bunker only)"],
        "target": 4.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 4.0, "amber": 8.0, "red": 16.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 18,
        "code": "KPI-18",
        "name": "Idle Time at Berth",
        "category": "Berthing and at berth",
        "description": "Idle alongside time divided by total berth stay duration * 100.",
        "formula": "(SUM(idle_hours) / SUM(berth_stay_hours)) * 100",
        "numerator": "Total non-working alongside hours",
        "denominator": "Total berth stay hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Completed berthed calls",
        "required_events": ["ALL_FAST_ARRIVAL", "CARGO_START", "CARGO_END", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["utc_value"],
        "exclusions": ["Zero denominator calls"],
        "target": 15.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 15.0, "amber": 25.0, "red": 40.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 19,
        "code": "KPI-19",
        "name": "Number of Vessel Shifts",
        "category": "Berthing and at berth",
        "description": "Total count of vessel shifting movements executed between berths or along berth.",
        "formula": "COUNT(shifting_events)",
        "numerator": "Count of executed shifting stages",
        "denominator": "None (count)",
        "unit": "shifts",
        "aggregation_method": "COUNT",
        "eligible_population": "All active calls",
        "required_events": ["SHIFT_PILOT_ON_BOARD", "SHIFT_ALL_FAST"],
        "required_fields": ["utc_value"],
        "exclusions": [],
        "target": 8.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 8.0, "amber": 15.0, "red": 25.0},
        "owner": "Harbour Master",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 20,
        "code": "KPI-20",
        "name": "Shifting Time",
        "category": "Berthing and at berth",
        "description": "Sum of shifting durations divided by completed shifts.",
        "formula": "AVG(SHIFT_ALL_FAST - SHIFT_PILOT_ON_BOARD)",
        "numerator": "Sum of shifting durations",
        "denominator": "Completed shift count",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Calls executing optional shifting",
        "required_events": ["SHIFT_PILOT_ON_BOARD", "SHIFT_ALL_FAST"],
        "required_fields": ["utc_value"],
        "exclusions": ["Calls without shift stages"],
        "target": 2.5,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 2.5, "amber": 4.0, "red": 6.0},
        "owner": "Harbour Master",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 21,
        "code": "KPI-21",
        "name": "Berth Productivity",
        "category": "Berthing and at berth",
        "description": "Total container moves divided by crane-hours. (Ensures the formula does not multiply by crane count twice if crane-hours are already summed per spec §11).",
        "formula": "SUM(container_moves) / SUM(working_hours)",
        "numerator": "Total container moves (or TEU)",
        "denominator": "Summed crane working hours across all deployed resources",
        "unit": "moves/crane-hr",
        "aggregation_method": "RATIO",
        "eligible_population": "Container vessel calls with cargo operations",
        "required_events": ["CARGO_START", "CARGO_END"],
        "required_fields": ["actual_quantity", "working_hours"],
        "exclusions": ["Non-container vessel calls"],
        "target": 28.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 28.0, "amber": 22.0, "red": 16.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 22,
        "code": "KPI-22",
        "name": "Berth Utilisation Ratio",
        "category": "Berthing and at berth",
        "description": "Productive working berth hours divided by available berth hours over reporting period * 100.",
        "formula": "(SUM(cargo_working_hours) / available_berth_hours) * 100",
        "numerator": "Productive working cargo hours alongside",
        "denominator": "Available theoretical berth hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Commercial working berths",
        "required_events": ["CARGO_START", "CARGO_END"],
        "required_fields": ["working_hours"],
        "exclusions": [],
        "target": 55.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 55.0, "amber": 40.0, "red": 30.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },

    # ── Cargo handling ────────────────────────────────────────────────────────
    {
        "kpi_number": 23,
        "code": "KPI-23",
        "name": "Cargo Handled in MT",
        "category": "Cargo handling",
        "description": "Total metric tonnes of bulk/general cargo handled during the period.",
        "formula": "SUM(actual_quantity) WHERE unit = 'MT'",
        "numerator": "Total actual cargo metric tonnes",
        "denominator": "None (sum)",
        "unit": "MT",
        "aggregation_method": "SUM",
        "eligible_population": "Cargo operations with unit='MT'",
        "required_events": ["CARGO_START", "CARGO_END"],
        "required_fields": ["actual_quantity", "unit"],
        "exclusions": ["Container TEU or vehicle Unit operations"],
        "target": 500000.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 500000.0, "amber": 400000.0, "red": 300000.0},
        "owner": "Commercial Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 24,
        "code": "KPI-24",
        "name": "Container Traffic in TEUs",
        "category": "Cargo handling",
        "description": "Total container traffic in TEUs (loaded + unloaded + transshipped, with configured treatment of restows).",
        "formula": "SUM(actual_quantity) WHERE unit = 'TEU'",
        "numerator": "Summed container TEU moves",
        "denominator": "None (sum)",
        "unit": "TEU",
        "aggregation_method": "SUM",
        "eligible_population": "Container cargo operations",
        "required_events": ["CARGO_START", "CARGO_END"],
        "required_fields": ["actual_quantity", "unit"],
        "exclusions": ["Bulk MT operations"],
        "target": 50000.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 50000.0, "amber": 35000.0, "red": 20000.0},
        "owner": "Commercial Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 25,
        "code": "KPI-25",
        "name": "Voyage Productivity",
        "category": "Cargo handling",
        "description": "Total container moves or cargo throughput divided by vessel calls.",
        "formula": "SUM(actual_quantity) / COUNT(DISTINCT vessel_call_id)",
        "numerator": "Sum of cargo quantity",
        "denominator": "Distinct vessel calls",
        "unit": "moves/call",
        "aggregation_method": "AVG",
        "eligible_population": "Active completed vessel calls with cargo operations",
        "required_events": ["CARGO_START", "CARGO_END"],
        "required_fields": ["actual_quantity"],
        "exclusions": ["Bunkering-only calls"],
        "target": 2000.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 2000.0, "amber": 1200.0, "red": 800.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 26,
        "code": "KPI-26",
        "name": "First Container Lift Time",
        "category": "Cargo handling",
        "description": "Average duration from All Fast (or berthing reference point) to first container lifted.",
        "formula": "AVG(FIRST_CONTAINER_LIFT - ALL_FAST_ARRIVAL)",
        "numerator": "Elapsed hours from all fast to first lift",
        "denominator": "Container vessel calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Container calls",
        "required_events": ["ALL_FAST_ARRIVAL", "FIRST_CONTAINER_LIFT"],
        "required_fields": ["utc_value"],
        "exclusions": ["Non-container calls"],
        "target": 0.75,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 0.75, "amber": 1.5, "red": 3.0},
        "owner": "Terminal Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["TOS_CRANE_LOG"],
        "is_primary": True,
    },
    {
        "kpi_number": 27,
        "code": "KPI-27",
        "name": "Average Ship Berth-Day Output",
        "category": "Cargo handling",
        "description": "Total cargo handled divided by ship berth-days (berth stay in days).",
        "formula": "SUM(actual_quantity) / (SUM(berth_stay_hours) / 24.0)",
        "numerator": "Total cargo handled (TEU or MT)",
        "denominator": "Total ship berth days",
        "unit": "units/berth-day",
        "aggregation_method": "RATIO",
        "eligible_population": "Vessel calls alongside berth",
        "required_events": ["ALL_FAST_ARRIVAL", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["actual_quantity"],
        "exclusions": ["Calls with zero berth stay"],
        "target": 3500.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 3500.0, "amber": 2500.0, "red": 1500.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 28,
        "code": "KPI-28",
        "name": "Number of Cranes per Vessel",
        "category": "Cargo handling",
        "description": "Average number of cranes deployed per worked vessel call.",
        "formula": "AVG(resources_deployed)",
        "numerator": "Sum of deployed resources",
        "denominator": "Worked vessel calls",
        "unit": "cranes",
        "aggregation_method": "AVG",
        "eligible_population": "Calls with crane assignments",
        "required_events": ["CARGO_START", "CARGO_END"],
        "required_fields": ["resources_deployed"],
        "exclusions": [],
        "target": 2.5,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 2.5, "amber": 2.0, "red": 1.5},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 29,
        "code": "KPI-29",
        "name": "Equipment Downtime",
        "category": "Cargo handling",
        "description": "Validated crane/equipment downtime divided by total equipment operating time * 100.",
        "formula": "(SUM(downtime_hours) / SUM(working_hours)) * 100",
        "numerator": "Total recorded downtime hours",
        "denominator": "Total gross operating hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Crane operations with downtime tracking",
        "required_events": [],
        "required_fields": ["downtime_hours", "working_hours"],
        "exclusions": [],
        "target": 3.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 3.0, "amber": 6.0, "red": 10.0},
        "owner": "Engineering",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 30,
        "code": "KPI-30",
        "name": "Crane Moves per Hour per Crane",
        "category": "Cargo handling",
        "description": "Total container moves divided by summed productive crane-hours (spec §11).",
        "formula": "SUM(actual_quantity) / SUM(working_hours * resources_deployed)",
        "numerator": "Total container moves",
        "denominator": "Summed individual crane hours across deployed cranes",
        "unit": "moves/crane-hr",
        "aggregation_method": "RATIO",
        "eligible_population": "Container calls with crane logs",
        "required_events": [],
        "required_fields": ["actual_quantity", "working_hours", "resources_deployed"],
        "exclusions": ["Bulk and passenger operations"],
        "target": 25.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 25.0, "amber": 20.0, "red": 15.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },

    # ── Yard operations (NO_SOURCE_DATA in fixture) ───────────────────────────
    {
        "kpi_number": 31,
        "code": "KPI-31",
        "name": "Import Container Dwell Time",
        "category": "Yard operations",
        "description": "Average elapsed time from container vessel discharge to gate exit.",
        "formula": "AVG(GATE_OUT - CONTAINER_DISCHARGE)",
        "numerator": "Sum of import dwell hours",
        "denominator": "Exited import containers",
        "unit": "days",
        "aggregation_method": "AVG",
        "eligible_population": "Import containers",
        "required_events": ["CONTAINER_DISCHARGE", "GATE_OUT"],
        "required_fields": ["container_id"],
        "exclusions": ["Transshipment containers"],
        "target": 3.5,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 3.5, "amber": 5.0, "red": 7.0},
        "owner": "Yard Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["YARD_TOS", "GATE_OCR"],
        "is_primary": True,
    },
    {
        "kpi_number": 32,
        "code": "KPI-32",
        "name": "Export Container Dwell Time",
        "category": "Yard operations",
        "description": "Average elapsed time from container gate-in to vessel loading.",
        "formula": "AVG(CONTAINER_LOAD - GATE_IN)",
        "numerator": "Sum of export dwell hours",
        "denominator": "Loaded export containers",
        "unit": "days",
        "aggregation_method": "AVG",
        "eligible_population": "Export containers",
        "required_events": ["GATE_IN", "CONTAINER_LOAD"],
        "required_fields": ["container_id"],
        "exclusions": [],
        "target": 2.5,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 2.5, "amber": 4.0, "red": 6.0},
        "owner": "Yard Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["YARD_TOS", "GATE_OCR"],
        "is_primary": True,
    },
    {
        "kpi_number": 33,
        "code": "KPI-33",
        "name": "Yard Utilisation Rate",
        "category": "Yard operations",
        "description": "Occupied yard ground slots divided by total available capacity * 100.",
        "formula": "(occupied_teu_slots / total_teu_slots) * 100",
        "numerator": "Occupied yard slots",
        "denominator": "Total operational yard slots",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Active container yard blocks",
        "required_events": [],
        "required_fields": ["occupied_slots", "total_slots"],
        "exclusions": ["Blocks undergoing pavement maintenance"],
        "target": 70.0,
        "target_direction": "BAND",
        "thresholds": {"green": 75.0, "amber": 85.0, "red": 92.0},
        "owner": "Yard Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["YARD_TOS"],
        "is_primary": True,
    },
    {
        "kpi_number": 34,
        "code": "KPI-34",
        "name": "Container Re-handling Rate",
        "category": "Yard operations",
        "description": "Non-productive container re-handles divided by total handled containers * 100.",
        "formula": "(rehandled_moves / total_moves) * 100",
        "numerator": "Productive and unproductive re-handles",
        "denominator": "Total gross yard moves",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Container yard stacks",
        "required_events": [],
        "required_fields": ["rehandle_moves", "gross_moves"],
        "exclusions": [],
        "target": 12.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 12.0, "amber": 18.0, "red": 25.0},
        "owner": "Yard Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["YARD_TOS_EQUIPMENT"],
        "is_primary": True,
    },
    {
        "kpi_number": 35,
        "code": "KPI-35",
        "name": "Yard Productivity",
        "category": "Yard operations",
        "description": "Total container yard moves divided by RTG/RMG crane-hours.",
        "formula": "yard_moves / yard_crane_hours",
        "numerator": "Total container moves in yard",
        "denominator": "Yard crane working hours",
        "unit": "moves/crane-hr",
        "aggregation_method": "RATIO",
        "eligible_population": "Yard crane operations",
        "required_events": [],
        "required_fields": ["yard_moves", "crane_hours"],
        "exclusions": [],
        "target": 18.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 18.0, "amber": 14.0, "red": 10.0},
        "owner": "Yard Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["YARD_TOS_EQUIPMENT"],
        "is_primary": True,
    },

    # ── Gate and landside (NO_SOURCE_DATA in fixture) ─────────────────────────
    {
        "kpi_number": 36,
        "code": "KPI-36",
        "name": "Truck Gate Turnaround",
        "category": "Gate and landside",
        "description": "Elapsed duration from terminal gate-in to gate-out for external road trucks.",
        "formula": "AVG(GATE_OUT - GATE_IN)",
        "numerator": "Total truck time on terminal",
        "denominator": "Total processed external trucks",
        "unit": "minutes",
        "aggregation_method": "AVG",
        "eligible_population": "External road trucks",
        "required_events": ["GATE_IN", "GATE_OUT"],
        "required_fields": ["truck_id"],
        "exclusions": ["Trucks detained for customs physical inspection"],
        "target": 45.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 45.0, "amber": 60.0, "red": 90.0},
        "owner": "Landside Logistics",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["GATE_OCR", "APPOINTMENT_SYSTEM"],
        "is_primary": True,
    },
    {
        "kpi_number": 37,
        "code": "KPI-37",
        "name": "Gate Transactions per Hour",
        "category": "Gate and landside",
        "description": "Total gate transactions completed per lane-hour.",
        "formula": "gate_transactions / active_lane_hours",
        "numerator": "Total completed gate transactions",
        "denominator": "Active operational lane-hours",
        "unit": "trucks/lane-hr",
        "aggregation_method": "RATIO",
        "eligible_population": "Terminal gate lanes",
        "required_events": [],
        "required_fields": ["transactions", "lane_hours"],
        "exclusions": ["Closed gate lanes"],
        "target": 30.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 30.0, "amber": 22.0, "red": 15.0},
        "owner": "Landside Logistics",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["GATE_OCR"],
        "is_primary": True,
    },
    {
        "kpi_number": 38,
        "code": "KPI-38",
        "name": "Truck Waiting at Entry",
        "category": "Gate and landside",
        "description": "Queuing duration outside terminal from gate arrival to gate-in barrier entry.",
        "formula": "AVG(GATE_IN - GATE_ARRIVAL)",
        "numerator": "Sum of road queue duration",
        "denominator": "Arriving trucks",
        "unit": "minutes",
        "aggregation_method": "AVG",
        "eligible_population": "Arriving container hauliers",
        "required_events": ["GATE_ARRIVAL", "GATE_IN"],
        "required_fields": ["truck_id"],
        "exclusions": ["Trucks arriving outside appointment window"],
        "target": 15.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 15.0, "amber": 30.0, "red": 60.0},
        "owner": "Landside Logistics",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["GATE_OCR", "ROAD_QUEUE_SENSORS"],
        "is_primary": True,
    },
    {
        "kpi_number": 39,
        "code": "KPI-39",
        "name": "Rail Dwell Time",
        "category": "Gate and landside",
        "description": "Average dwell time of intermodal rail wagons on terminal sidings from arrival to dispatch.",
        "formula": "AVG(RAIL_DISPATCH - RAIL_ARRIVAL)",
        "numerator": "Total rail wagon dwell hours",
        "denominator": "Dispatched rail wagons",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Intermodal rail wagons",
        "required_events": ["RAIL_ARRIVAL", "RAIL_DISPATCH"],
        "required_fields": ["train_id"],
        "exclusions": ["Damaged wagons held for mechanical repair"],
        "target": 12.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 12.0, "amber": 18.0, "red": 24.0},
        "owner": "Intermodal Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["RAIL_OPERATOR_TOS"],
        "is_primary": True,
    },
    {
        "kpi_number": 40,
        "code": "KPI-40",
        "name": "Rail Rake Handling Time",
        "category": "Gate and landside",
        "description": "Elapsed time to load and discharge a complete train rake.",
        "formula": "AVG(RAIL_OPS_END - RAIL_OPS_START)",
        "numerator": "Elapsed rake working hours",
        "denominator": "Worked rail rakes",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Container rail rakes",
        "required_events": ["RAIL_OPS_START", "RAIL_OPS_END"],
        "required_fields": ["train_id"],
        "exclusions": [],
        "target": 4.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 4.0, "amber": 6.0, "red": 10.0},
        "owner": "Intermodal Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["RAIL_OPERATOR_TOS"],
        "is_primary": True,
    },

    # ── Departure and turnaround ──────────────────────────────────────────────
    {
        "kpi_number": 41,
        "code": "KPI-41",
        "name": "Turnaround Time",
        "category": "Departure and turnaround",
        "description": "Average total turnaround duration from Anchorage Arrival (or ATA if no anchorage) to Departure (ATD), distinct from the pure ATA-to-ATD turnaround (spec §11).",
        "formula": "AVG(ATD - ANCHORAGE_ARRIVAL)",
        "numerator": "Sum of total port turnaround hours",
        "denominator": "Count of departed vessel calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Completed vessel calls",
        "required_events": ["ANCHORAGE_ARRIVAL", "ATD"],
        "required_fields": ["utc_value"],
        "exclusions": ["Quarantined calls", "Documented litigation/engine repair holds"],
        "target": 36.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 36.0, "amber": 60.0, "red": 120.0},
        "owner": "Harbour Master",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 42,
        "code": "KPI-42",
        "name": "Berth Turnaround",
        "category": "Departure and turnaround",
        "description": "Average interval between All Fast and Last Line Untied (berth departure).",
        "formula": "AVG(LAST_LINE_UNTIED_SAILING - ALL_FAST_ARRIVAL)",
        "numerator": "Sum of alongside durations",
        "denominator": "Completed berthed calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Completed berthed calls",
        "required_events": ["ALL_FAST_ARRIVAL", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["utc_value"],
        "exclusions": ["Quarantined calls"],
        "target": 24.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 24.0, "amber": 48.0, "red": 72.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 43,
        "code": "KPI-43",
        "name": "Average Outward Movement",
        "category": "Departure and turnaround",
        "description": "Average duration from departure unberthing / pilot boarding to clearing Port Limit Out (or breakwater out).",
        "formula": "AVG(BREAKWATER_OUT - PILOT_ON_BOARD_SAILING)",
        "numerator": "Sum of outward transit durations",
        "denominator": "Departed calls",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Departed calls with sailing pilotage",
        "required_events": ["PILOT_ON_BOARD_SAILING", "BREAKWATER_OUT"],
        "required_fields": ["utc_value"],
        "exclusions": ["Quarantined calls"],
        "target": 1.25,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 1.2, "amber": 2.0, "red": 3.0},
        "owner": "Marine Pilotage",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 44,
        "code": "KPI-44",
        "name": "Average Outward Towage Duration",
        "category": "Departure and turnaround",
        "description": "Average duration of towage operations executed during departure unberthing.",
        "formula": "AVG(unberthing_towage_duration)",
        "numerator": "Total sailing tug service hours",
        "denominator": "Sailing towage operations",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Vessels requiring sailing towage",
        "required_events": ["FIRST_LINE_UNTIED_SAILING", "BREAKWATER_OUT"],
        "required_fields": ["service_type"],
        "exclusions": ["Unassisted unberthing calls"],
        "target": 0.8,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 0.8, "amber": 1.5, "red": 2.5},
        "owner": "Towage Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 45,
        "code": "KPI-45",
        "name": "Outward Movements per Day",
        "category": "Departure and turnaround",
        "description": "Average number of outward vessel departures handled per calendar day.",
        "formula": "COUNT(departures) / number_of_days",
        "numerator": "Total vessel departures in period",
        "denominator": "Calendar days in period",
        "unit": "departures/day",
        "aggregation_method": "RATIO",
        "eligible_population": "Completed vessel calls",
        "required_events": ["ATD"],
        "required_fields": ["utc_value"],
        "exclusions": [],
        "target": 4.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 4.0, "amber": 3.0, "red": 2.0},
        "owner": "Harbour Master",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },

    # ── Operational efficiency and coordination (NO_SOURCE_DATA) ───────────────
    {
        "kpi_number": 46,
        "code": "KPI-46",
        "name": "Crane Availability Ratio",
        "category": "Operational efficiency and coordination",
        "description": "Total available operational crane-hours divided by planned crane-hours * 100.",
        "formula": "(available_crane_hours / planned_crane_hours) * 100",
        "numerator": "Available crane hours",
        "denominator": "Planned operating crane hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Ship-to-shore gantry cranes",
        "required_events": [],
        "required_fields": [],
        "exclusions": [],
        "target": 95.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 95.0, "amber": 90.0, "red": 80.0},
        "owner": "Engineering",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["TOS_ENGINEERING_SCADA"],
        "is_primary": True,
    },
    {
        "kpi_number": 47,
        "code": "KPI-47",
        "name": "Average Moves per Gang Shift",
        "category": "Operational efficiency and coordination",
        "description": "Container moves achieved per stevedore gang shift.",
        "formula": "total_moves / stevedore_gang_shifts",
        "numerator": "Total container moves",
        "denominator": "Gang shifts deployed",
        "unit": "moves/gang-shift",
        "aggregation_method": "RATIO",
        "eligible_population": "Stevedoring operations",
        "required_events": [],
        "required_fields": [],
        "exclusions": [],
        "target": 180.0,
        "target_direction": "HIGHER_IS_BETTER",
        "thresholds": {"green": 180.0, "amber": 140.0, "red": 100.0},
        "owner": "Stevedoring Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["LABOUR_MANAGEMENT_SYSTEM"],
        "is_primary": True,
    },
    {
        "kpi_number": 48,
        "code": "KPI-48",
        "name": "Unproductive Moves Ratio",
        "category": "Operational efficiency and coordination",
        "description": "Unproductive hatch cover and gear moves divided by total crane moves * 100.",
        "formula": "(unproductive_moves / total_moves) * 100",
        "numerator": "Unproductive equipment cycles",
        "denominator": "Total equipment cycles",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Crane moves",
        "required_events": [],
        "required_fields": [],
        "exclusions": [],
        "target": 5.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 5.0, "amber": 8.0, "red": 12.0},
        "owner": "Terminal Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["TOS_CRANE_LOG"],
        "is_primary": True,
    },

    # ── Resource utilisation ──────────────────────────────────────────────────
    {
        "kpi_number": 49,
        "code": "KPI-49",
        "name": "Pilot Utilisation",
        "category": "Resource utilisation",
        "description": "Pilot on-duty service hours divided by available scheduled pilot hours * 100.",
        "formula": "(pilot_service_hours / available_scheduled_pilot_hours) * 100",
        "numerator": "Actual pilotage service hours performed",
        "denominator": "Total scheduled pilot rostered hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Marine pilots on duty",
        "required_events": [],
        "required_fields": ["service_type", "served_time"],
        "exclusions": [],
        "target": 75.0,
        "target_direction": "BAND",
        "thresholds": {"green": 75.0, "amber": 85.0, "red": 92.0},
        "owner": "Marine Pilotage",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 50,
        "code": "KPI-50",
        "name": "Tug Utilisation",
        "category": "Resource utilisation",
        "description": "Tug operational service hours divided by available tug operational hours * 100.",
        "formula": "(tug_service_hours / available_tug_operational_hours) * 100",
        "numerator": "Actual towage service hours performed",
        "denominator": "Total available tug fleet operational hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Tug fleet in service",
        "required_events": [],
        "required_fields": ["service_type", "served_time"],
        "exclusions": ["Tugs under scheduled maintenance"],
        "target": 65.0,
        "target_direction": "BAND",
        "thresholds": {"green": 65.0, "amber": 75.0, "red": 88.0},
        "owner": "Towage Operations",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 51,
        "code": "KPI-51",
        "name": "Berth Occupancy",
        "category": "Resource utilisation",
        "description": "Vessel berth time divided by available berth time * 100. (Duplicate concept of KPI-14; registered as ALIAS of KPI-14 to prevent double-counting per spec §11).",
        "formula": "ALIAS(KPI-14)",
        "numerator": "Alias of KPI-14",
        "denominator": "Alias of KPI-14",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Alias of KPI-14",
        "required_events": ["ALL_FAST_ARRIVAL", "LAST_LINE_UNTIED_SAILING"],
        "required_fields": ["utc_value"],
        "exclusions": [],
        "target": 65.0,
        "target_direction": "BAND",
        "thresholds": {"green": 70.0, "amber": 80.0, "red": 90.0},
        "owner": "Terminal Operations",
        "availability_status": "COMPUTED",
        "is_primary": False,
        "alias_of_code": "KPI-14",
    },
    {
        "kpi_number": 52,
        "code": "KPI-52",
        "name": "Crane Utilisation",
        "category": "Resource utilisation",
        "description": "Productive crane working hours divided by available crane hours * 100.",
        "formula": "(working_crane_hours / available_crane_hours) * 100",
        "numerator": "Productive crane working hours",
        "denominator": "Total available operational crane hours",
        "unit": "%",
        "aggregation_method": "RATIO",
        "eligible_population": "Quayside gantry cranes",
        "required_events": [],
        "required_fields": [],
        "exclusions": [],
        "target": 70.0,
        "target_direction": "BAND",
        "thresholds": {"green": 70.0, "amber": 80.0, "red": 90.0},
        "owner": "Terminal Operations",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["TOS_CRANE_LOG"],
        "is_primary": True,
    },
    {
        "kpi_number": 53,
        "code": "KPI-53",
        "name": "Average Tug Response",
        "category": "Resource utilisation",
        "description": "Average Tug Arrival minus Request duration. (Duplicate concept of KPI-11; registered as ALIAS of KPI-11 to prevent double-counting per spec §11).",
        "formula": "ALIAS(KPI-11)",
        "numerator": "Alias of KPI-11",
        "denominator": "Alias of KPI-11",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Alias of KPI-11",
        "required_events": [],
        "required_fields": ["requested_time", "served_time"],
        "exclusions": [],
        "target": 0.75,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 0.8, "amber": 1.5, "red": 2.5},
        "owner": "Towage Operations",
        "availability_status": "COMPUTED",
        "is_primary": False,
        "alias_of_code": "KPI-11",
    },
    {
        "kpi_number": 54,
        "code": "KPI-54",
        "name": "Average Pilot Response",
        "category": "Resource utilisation",
        "description": "Average duration between Pilot Request and Pilot On Board.",
        "formula": "AVG(PILOT_ON_BOARD_ARRIVAL - PILOT_REQUEST_ARRIVAL)",
        "numerator": "Sum of pilot request-to-boarding intervals",
        "denominator": "Served pilotage requests",
        "unit": "hours",
        "aggregation_method": "AVG",
        "eligible_population": "Pilotage service requests",
        "required_events": ["PILOT_REQUEST_ARRIVAL", "PILOT_ON_BOARD_ARRIVAL"],
        "required_fields": ["utc_value"],
        "exclusions": ["Cancelled requests"],
        "target": 1.5,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 1.5, "amber": 2.5, "red": 4.0},
        "owner": "Marine Pilotage",
        "availability_status": "COMPUTED",
        "is_primary": True,
    },
    {
        "kpi_number": 55,
        "code": "KPI-55",
        "name": "Average Crane Downtime",
        "category": "Resource utilisation",
        "description": "Total equipment downtime divided by incident count, with optional vessel-level total downtime / worked vessel calls.",
        "formula": "SUM(downtime_hours) / COUNT(incidents)",
        "numerator": "Total downtime hours",
        "denominator": "Count of recorded equipment breakdown incidents",
        "unit": "hours/incident",
        "aggregation_method": "AVG",
        "eligible_population": "Recorded crane incidents",
        "required_events": [],
        "required_fields": [],
        "exclusions": [],
        "target": 1.0,
        "target_direction": "LOWER_IS_BETTER",
        "thresholds": {"green": 1.0, "amber": 2.0, "red": 4.0},
        "owner": "Engineering",
        "availability_status": "NO_SOURCE_DATA",
        "required_source_systems": ["CMMS_MAINTENANCE_LOG"],
        "is_primary": True,
    },
]


def ensure_kpi_registry(db: Session) -> Dict[str, KPI]:
    """Ensures all 55 KPIs from spec §11 exist in analytics.kpi with correct metadata,

    formula versions, and primary/alias links.
    """
    existing_kpis = {k.code: k for k in db.execute(select(KPI)).scalars().all() if k.code}
    # Also check by name
    existing_by_name = {k.name: k for k in db.execute(select(KPI)).scalars().all()}

    kpi_map: Dict[str, KPI] = {}

    for item in KPI_REGISTRY_DEFINITIONS:
        code = item["code"]
        name = item["name"]

        # Find existing by code or name
        kpi = existing_kpis.get(code) or existing_by_name.get(name)

        if not kpi:
            kpi = KPI(
                name=name,
                code=code,
                kpi_number=item["kpi_number"],
                category=item["category"],
                description=item["description"],
                formula=item["formula"],
                numerator=item["numerator"],
                denominator=item["denominator"],
                unit=item["unit"],
                eligible_population=item["eligible_population"],
                required_events=item.get("required_events", []),
                required_fields=item.get("required_fields", []),
                exclusions=item.get("exclusions", []),
                aggregation_method=item.get("aggregation_method", "AVG"),
                vessel_applicability=item.get("vessel_applicability", "All"),
                target=item.get("target"),
                target_direction=item.get("target_direction", "LOWER_IS_BETTER"),
                thresholds=item.get("thresholds", {}),
                owner=item.get("owner", "Operations"),
                is_primary=item.get("is_primary", True),
                availability_status=item.get("availability_status", "COMPUTED"),
                required_source_systems=item.get("required_source_systems", []),
                effective_from=datetime(2026, 1, 1, tzinfo=timezone.utc),
            )
            db.add(kpi)
            db.flush()
        else:
            # Update metadata
            kpi.name = name
            kpi.code = code
            kpi.kpi_number = item["kpi_number"]
            kpi.category = item["category"]
            kpi.description = item["description"]
            kpi.formula = item["formula"]
            kpi.numerator = item["numerator"]
            kpi.denominator = item["denominator"]
            kpi.unit = item["unit"]
            kpi.eligible_population = item["eligible_population"]
            kpi.required_events = item.get("required_events", [])
            kpi.required_fields = item.get("required_fields", [])
            kpi.exclusions = item.get("exclusions", [])
            kpi.aggregation_method = item.get("aggregation_method", "AVG")
            kpi.vessel_applicability = item.get("vessel_applicability", "All")
            kpi.target = item.get("target")
            kpi.target_direction = item.get("target_direction", "LOWER_IS_BETTER")
            kpi.thresholds = item.get("thresholds", {})
            kpi.owner = item.get("owner", "Operations")
            kpi.is_primary = item.get("is_primary", True)
            kpi.availability_status = item.get("availability_status", "COMPUTED")
            kpi.required_source_systems = item.get("required_source_systems", [])
            db.flush()

        # Ensure initial formula version
        formula_ver = db.execute(
            select(KPIFormulaVersion).where(
                KPIFormulaVersion.kpi_id == kpi.id,
                KPIFormulaVersion.version == "1.0",
            )
        ).scalar_one_or_none()

        if not formula_ver:
            formula_ver = KPIFormulaVersion(
                kpi_id=kpi.id,
                version="1.0",
                expression=item["formula"],
            )
            db.add(formula_ver)
            db.flush()

        kpi_map[code] = kpi

    # Link alias relationships
    for item in KPI_REGISTRY_DEFINITIONS:
        alias_code = item.get("alias_of_code")
        if alias_code and alias_code in kpi_map:
            current_kpi = kpi_map[item["code"]]
            primary_kpi = kpi_map[alias_code]
            current_kpi.alias_of_id = primary_kpi.id
            current_kpi.is_primary = False
            db.flush()

    db.commit()
    return kpi_map
